import sys
from custome_errors import *
sys.excepthook=my_excepthook
import datetime
import wx
import settings,gui,guiTools
settings.language.init_translation()
class main(wx.Frame):
    def __init__(self):
        super().__init__(None,-1,title=settings.app.name + _(" version ") + str(settings.app.version))
        panel=wx.Panel(self)
        sizer=wx.BoxSizer()
        lbl_birth_year = wx.StaticText(panel, label='Year:')
        self.txt_birth_year = wx.TextCtrl(panel)
        lbl_birth_month = wx.StaticText(panel, label='Month:')
        self.txt_birth_month = wx.TextCtrl(panel)
        lbl_birth_day = wx.StaticText(panel, label='Day:')
        self.txt_birth_day = wx.TextCtrl(panel)
        calc_btn = wx.Button(panel, -1, 'Calculate')
        self.Bind(wx.EVT_BUTTON, self.Calculate, calc_btn)
        wx.StaticText(panel , -1, "value")
        self.value= wx.ListBox(panel, -1,)
        self.settings=wx.Button(panel,-1,_("settings"))
        self.Bind(wx.EVT_BUTTON,lambda event:settings.settings(self).Show(),self.settings)
        sizer.Add(self.settings)
        panel.SetSizer(sizer)
        self.Bind(wx.EVT_CLOSE,self.CloseEvent)
        mb=wx.MenuBar()
        help=wx.Menu()
        cus=wx.Menu()
        telegram=cus.Append(-1,"telegram")
        self.Bind(wx.EVT_MENU,lambda event:guiTools.OpenLink(self,"https://t.me/mesteranasm"),telegram)
        telegramChannel=cus.Append(-1,_("telegram channel"))
        self.Bind(wx.EVT_MENU,lambda event:guiTools.OpenLink(self,"https://t.me/tprogrammers"),telegramChannel)
        github=cus.Append(-1,"github")
        self.Bind(wx.EVT_MENU,lambda event:guiTools.OpenLink(self,"https://Github.com/mesteranas"),github)
        x=cus.Append(-1,"X")
        self.Bind(wx.EVT_MENU,lambda event:guiTools.OpenLink(self,"https://x.com/mesteranasm"),x)
        email=cus.Append(-1,_("email"))
        self.Bind(wx.EVT_MENU,lambda event:guiTools.sendEmail("anasformohammed@gmail.com",settings.settings_handler.appName,"hello"),email)
        help.AppendSubMenu(cus,_("contect us"))
        projetGithub=help.Append(-1,_("visit project on github"))
        self.Bind(wx.EVT_MENU,lambda event:guiTools.OpenLink(self,"https://github.com/mesteranas/{}_gui_wx".format(settings.settings_handler.appName)),projetGithub)
        donate=help.Append(-1,_("donate"))
        self.Bind(wx.EVT_MENU,lambda event:guiTools.OpenLink(self,"https://www.paypal.me/AMohammed231"),donate)
        about=help.Append(-1,_("about"))
        self.Bind(wx.EVT_MENU,lambda event:wx.MessageBox(_("{} version: {} description: {} developer: {}").format(settings.app.name,settings.app.version,settings.app.description,settings.app.creater),_("about")),about)
        mb.Append(help,_("help"))
        self.SetMenuBar(mb)
    def CloseEvent(self,event):
        if settings.settings_handler.get("g","exitdialog")=="True":
            guiTools.ExitDialog(self).Show()
        else:
            wx.Exit()
    def Calculate(self, event):
        birth_year = int(self.txt_birth_year.GetValue())
        birth_month = int(self.txt_birth_month.GetValue())
        birth_day = int(self.txt_birth_day.GetValue())
        date_of_birth = datetime.datetime(birth_year, birth_month, birth_day)
        today = datetime.datetime.today()
        age = today.year - date_of_birth.year - ((today.month, today.day) < (date_of_birth.month, date_of_birth.day))
        M_manth=int(age*12)
        M_week=int(age*48)
        M_day=int(age*365)
        M_hour=int(age*15330)
        m_mantins=int(age*525600)
        m_scends=int(age*31536000)
        M_ms=int(age*1892160000)
        self.value.Set([f"Years:{age}",f"munths:{M_manth}",f"weeks:{M_week}",f"days:{M_day}",f"hours:{M_hour}",f"minutes:{m_mantins}",f"Seconds:{m_scends}",f"milliseconds:{M_ms}"])
app=wx.App()
w=main()
w.Show()
app.MainLoop()